# Generated by Django 5.1 on 2024-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_favoritemovie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
